import ContactFormNewPage from '@domains/ContactFormNewPage'
import Head from 'next/head'

export default function AddContact() {
  return (
    <>
      <Head>
        <title>Add Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <ContactFormNewPage />
    </>
  )
}
